[project]
name = "job-agent-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "skumarudel", email = "skumarudel@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "google-api-python-client>=2.198.0",
    "google-auth>=2.56.2",
]

[project.scripts]
job-agent-lab = "job_agent_lab:main"

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
]
